name: Publish livekit-plugins-aws

on:
  workflow_dispatch

jobs:
  call-publish-workflow:
    uses: ./.github/workflows/publish-package.yml
    with:
      package_name: 'livekit-plugins/livekit-plugins-aws'
      package_module: 'livekit.plugins.aws'
    secrets: inherit
